#pragma once
#include "Level/LevelBase.h"

class LevelZero:
	public LevelBase
{
public:
	LevelZero();
	~LevelZero();

	std::shared_ptr<Ike> ike;
	std::shared_ptr<Dorcas> dorcas;
	std::shared_ptr<Serra> serra;
	std::shared_ptr<EnemyBanditHeader> banditLeader;
	std::shared_ptr<EnemyBandit> bandit1;
	std::shared_ptr<EnemyBandit> bandit2;
	std::shared_ptr<EnemyBandit> bandit3;
	std::shared_ptr<EnemyBandit> bandit4;
	std::shared_ptr<EnemyBandit> bandit5;
	std::shared_ptr<EnemyBandit> bandit6;
	std::shared_ptr<EnemyBandit> bandit7;

	void update() override;

	const int mapping[Globals::mapWidth][Globals::mapHeight] =
	{				/*0*/		/*1*/		/*2*/		/*3*/		/*4*/		/*5*/		/*6*/		/*7*/		/*8*/		/*9*/		/*10*/		/*11*/		/*12*/		/*13*/		/*14*/		/*15*/		/*16*/		/*17*/		/*18*/		/*19*/
		/*0*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	 SNOW_TREE,	 SNOW_TREE,	 SNOW_TREE,	FRONT_EDGE,	   GROUND,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE},

		/*1*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	 SNOW_TREE,	 SNOW_TREE,	SNOW_FIELD,	    GROUND,		 CAMP,	 SNOW_TREE,	 SNOW_TREE,	SNOW_FIELD,	SNOW_FIELD,		 RIVER,	SNOW_FIELD,	 SNOW_TREE,	SNOW_FIELD,		 RIVER,	SNOW_FIELD},

		/*2*/	{		GROUND,		  TREE,	 SNOW_TREE,	 SNOW_TREE,	 LEFT_EDGE,	 SNOW_TREE,	SNOW_FIELD,	SNOW_FIELD,	    GROUND,	   GROUND,	    GROUND,	 SNOW_TREE,	SNOW_FIELD,	SNOW_FIELD,		 RIVER,	SNOW_FIELD,	    GROUND,	SNOW_FIELD,		 RIVER,	SNOW_FIELD},

		/*3*/	{		GROUND,		  TREE,	 SNOW_TREE,	 SNOW_TREE,	 LEFT_EDGE,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		 RIVER,		 RIVER,	BRIDGE_VER,		 RIVER,		 RIVER,	SNOW_FIELD},

		/*4*/	{		GROUND,		  TREE,	 SNOW_TREE,	 SNOW_TREE,	 LEFT_EDGE,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	    GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*5*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	    GROUND,	    GROUND,	    GROUND,	    GROUND,	    GROUND,	    GROUND,	    GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*6*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*7*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	  LEFTCRNR,	FRONT_EDGE,	FRONT_EDGE,	RIGHTCRNR,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	  LEFTCRNR,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE},

		/*8*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 SNOW_TREE,	 SNOW_TREE,	 SNOW_TREE,	RIGHT_EDGE,	SNOW_FIELD,	SNOW_FIELD},

		/*9*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	SNOW_FIELD,	 SNOW_TREE,	   GROUND,	 SNOW_TREE,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 SNOW_TREE,	 SNOW_TREE,	 SNOW_TREE,	RIGHT_EDGE,	SNOW_FIELD,	SNOW_FIELD},

		/*10*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	SNOW_FIELD,	 SNOW_TREE,	   GROUND,	 SNOW_TREE,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 SNOW_TREE,	 SNOW_TREE,	 SNOW_TREE,	RIGHT_EDGE,	SNOW_FIELD,	SNOW_FIELD},

		/*11*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 LEFT_EDGE,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	 SNOW_TREE,	 SNOW_TREE,	 SNOW_TREE,	RIGHT_EDGE,	SNOW_FIELD,	SNOW_FIELD},

		/*12*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	  LEFTCRNR,	RIGHTCRNR,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	  LEFTCRNR,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	FRONT_EDGE,	 RIGHTCRNR,	SNOW_FIELD,	SNOW_FIELD},

		/*13*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,		  ROCK,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*14*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*15*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*16*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*17*/	{		GROUND,		GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	   GROUND,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},

		/*18*/	{		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		  TREE,	   GROUND,		  TREE,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND},

		/*19*/	{		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		  TREE,		  TREE,	   GROUND,		  TREE,		  TREE,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND,		GROUND}
	};
};

