#pragma once
#include "Level/LevelBase.h"

class LevelZero:
	public LevelBase
{
public:
	LevelZero(): LevelBase() {}
	LevelZero(std::shared_ptr<Model> model, std::shared_ptr<Shader> shader, std::shared_ptr<Texture> texture);
	~LevelZero();

	const int mapping[Globals::mapWidth][Globals::mapHeight] =
	{				/*0*/		/*1*/		/*2*/		/*3*/		/*4*/		/*5*/		/*6*/		/*7*/		/*8*/		/*9*/		/*10*/		/*11*/		/*12*/		/*13*/		/*14*/		/*15*/		/*16*/		/*17*/		/*18*/		/*19*/
		/*0*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*1*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*2*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*3*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*4*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*5*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*6*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*7*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*8*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*9*/	{		 RIVER,		 RIVER,		 RIVER,		 RIVER,	SNOW_FIELD,		 RIVER,		 RIVER,		 RIVER,		 RIVER,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*10*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*11*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*12*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*13*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*14*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*15*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*16*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*17*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*18*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD},
		/*19*/	{	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,		RIVER,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD,	SNOW_FIELD}
	};
};

